# Generated by Django 4.2 on 2025-06-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePerso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='hairstyles/')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='test@placeholder.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom_famille',
            field=models.CharField(default='HAGNIGBE', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='num_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service_choice',
            field=models.CharField(max_length=200),
        ),
    ]
