# Generated by Django 4.2 on 2025-06-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyle_app', '0002_demandeperso_reservation_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
